__all__ = [
    'device_timestamp_feature', \
    #'feature_acceleration_event', \
    'feature_accelerometer', \
    'feature_activity_recognition', \
    #'feature_analog', \
    #'feature_anomay_detection', \
    'feature_audio_scene_classification', \
    #'feature_battery', \
    'feature_beamforming', \
    #'feature_binary_content', \
    #'feature_carry_position', \
    #'feature_compass', \
    #'feature_co_sensor', \
    #'feature_dc_motor', \
    #'feature_direction_of_arrival', \
    #'feature_event_counter', \
    #'feature_extended_configuration', \
    #'feature_free_fall', \
    #'feature_gesture_navigation', \
    #'feature_gnss', \
    'feature_gyroscope', \
    'feature_humidity', \
    #'feature_json_nfc', \
    #'feature_luminosity', \
    'feature_machine_learning_core', \
    'feature_magnetometer', \
    #'feature_mems_gesture', \
    #'feature_mems_norm', \
    #'feature_mems_sensor_fusion', \
    #'feature_mems_sensor_fusion_compact', \
    #'feature_microphone_level', \
    #'feature_motion_intensity', \
    'feature_neai_anomaly_detection', \
    #'feature_neai_classification', \
    #'feature_pedometer', \
    #'feature_piano', \
    'feature_pressure', \
    'feature_proximity', \
    'feature_proximity_gesture', \
    #'feature_raw_pnpl', \
    #'feature_sd_logging', \
    'feature_stepper_motor', \
    'feature_stredl', \
    'feature_switch', \
    'feature_temperature', \
    'field'
]
